### ISSUE TITLE
[HW]  Pavan Kumar

### ISSUE THREAD

**Issue by pavanpulamathi** [datastaxdevs/workshop-intro-to-cassandra#202]
**Name:** PAVAN KUMAR
**Email:** pulamathi.pavan@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/pavan-kumar-pulamathi-5bab3429/
[CRUD Screenshots.docx](https://github.com/datastaxdevs/workshop-intro-to-cassandra/files/6678934/CRUD.Screenshots.docx)
[CRUD Screenshots.docx](https://github.com/datastaxdevs/workshop-intro-to-cassandra/files/6678936/CRUD.Screenshots.docx)
![Cassandra data Modeling - Homework](https://user-images.githubusercontent.com/86127861/122607503-48ce0600-d098-11eb-93ed-4dc51ced5623.PNG)
![Cassandra - CQL Homework](https://user-images.githubusercontent.com/86127861/122607514-4cfa2380-d098-11eb-9e7b-2e843134dad7.PNG)

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

<SCREENSHOT>

**Comment by HadesArchitect** [comment]
Hey **PAVAN KUMAR**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/jZezRVdBT16ubwKMGrjF4Q

**Comment by pavanpulamathi** [comment]
Thanks Aleks.
