### ISSUE TITLE
[HW] Rupam Mukherjee

### ISSUE THREAD

**Issue by RupamMukherjee** [datastaxdevs/workshop-intro-to-cassandra#204]
**Name:** Rupam Mukherjee
**Email:** rupammukherji1997@yahoo.com
**Linkedin Profile:** www.linkedin.com/in/rupam-mukherjee15497

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

<SCREENSHOT>

![Step II Workshop Practice Last Step(3e of Execute CRUD)](https://user-images.githubusercontent.com/46292971/122619357-ebdd4a80-d0ad-11eb-9304-f0b92f62b4b9.png)

![Step III Cassandra Data Modelling scenario (homework done)](https://user-images.githubusercontent.com/46292971/122619360-ed0e7780-d0ad-11eb-9e27-f61c4d54ffe7.png)

![Step III Cassandra Query Language_CQL scenario (homework done)](https://user-images.githubusercontent.com/46292971/122619362-eda70e00-d0ad-11eb-8579-3f052a1caf6b.png)

**Comment by HadesArchitect** [comment]
Hey **Rupam Mukherjee**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/BPyyUg2CRjGUFZ0E5ySyfw
