### ISSUE TITLE
[Cassandra Day India: CL Room (Workshops)] <Srinivas Nagesh Pammi>

### ISSUE THREAD

**Issue by npammi1** [datastaxdevs/workshop-intro-to-cassandra#244]
**Name:** Srinivas Nagesh Pammi
**Email:** npammi1@gmail.com
**Linkedin Profile:** www.linkedin.com/in/nagesh-srinivas-pammi-2438a58

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

Step 2a
******
![Step 2a](https://user-images.githubusercontent.com/14265418/125166087-8f0a1700-e1b7-11eb-97d5-304b31c2daa1.jpg)

Step 2b
******
![Step2b](https://user-images.githubusercontent.com/14265418/125166142-d98b9380-e1b7-11eb-93df-108b0eca8537.jpg)

Step 2c:
![Step 2c](https://user-images.githubusercontent.com/14265418/125166223-371fe000-e1b8-11eb-8004-9749845c8a90.jpg)

Step 3a:
![Step3a](https://user-images.githubusercontent.com/14265418/125166266-6e8e8c80-e1b8-11eb-8617-298009035515.jpg)

Step 3b and 3c:
![Step3b and 3c](https://user-images.githubusercontent.com/14265418/125166419-2328ae00-e1b9-11eb-881c-ee48ba313942.jpg)

Step 3d:
![Step3d](https://user-images.githubusercontent.com/14265418/125166475-64b95900-e1b9-11eb-8a1a-03204e90f20e.jpg)

Step 3e:
![Step3e](https://user-images.githubusercontent.com/14265418/125166500-9cc09c00-e1b9-11eb-97c9-64418484d2d7.jpg)

**Comment by npammi1** [comment]
Submitted home work. Kindly acknowledge.

**Comment by SonicDMG** [comment]
Hi Srinivas, thank you for your submission. Nice job getting through the core workshop materials. We are just missing screens from step 3 of the homework.
3. Complete the following short courses: [Cassandra Data Modeling](https://www.datastax.com/node/3272) and [Cassandra Query Language](https://www.datastax.com/dev/scenario/try-it-out-cassandra-query-language-cql). Take screenshots of the "Congratulations" page from each course.

**Comment by npammi1** [comment]
Here are screenshots as advised:
Cassandra Data Modelling:
***********
![image](https://user-images.githubusercontent.com/14265418/125616168-22fc4ffa-2e1d-4caf-9b64-20d2e4c156a4.png)

Cassandra Query Language
***************
![image](https://user-images.githubusercontent.com/14265418/125618876-72b5a638-6f0b-430b-a605-d061b45ab241.png)

**Comment by npammi1** [comment]
> Hi Srinivas, thank you for your submission. Nice job getting through the core workshop materials. We are just missing screens from step 3 of the homework.
> 3. Complete the following short courses: [Cassandra Data Modeling](https://www.datastax.com/node/3272) and [Cassandra Query Language](https://www.datastax.com/dev/scenario/try-it-out-cassandra-query-language-cql). Take screenshots of the "Congratulations" page from each course.

**Comment by HadesArchitect** [comment]
Hey **Srinivas Nagesh Pammi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/xvgScx_3Qqql5brfwgYzKw

**Comment by SonicDMG** [comment]
That was it Srinivas, thank you for following up.

**Comment by npammi1** [comment]
> Hey **Srinivas Nagesh Pammi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/xvgScx_3Qqql5brfwgYzKw

Thank you very much.  Also, can you please indicate when I may get voucher for Cassandra Certification. Thanks again.

**Comment by npammi1** [comment]
> Hey **Srinivas Nagesh Pammi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/xvgScx_3Qqql5brfwgYzKw

Hi Aleks,
Thank you very much.  Can you please also indicate when I may get voucher for Cassandra certification.  Will be keen to pursue certification.

Thank you again.
