### ISSUE TITLE
[HW] <Julian Nadarzy>

### ISSUE THREAD

**Issue by juliann** [datastaxdevs/workshop-intro-to-cassandra#255]
**Name:** Julian Nadarzy
**Email:** julian.nadarzy@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/julian-nadarzy-74b7b810/

Attach the homework screenshots below for both step II and step III:
-----------------------------------------
![a1](https://user-images.githubusercontent.com/1125748/127738741-529a6cce-ce7a-48f6-a3aa-e6e220a15d1a.jpg)
![a2](https://user-images.githubusercontent.com/1125748/127738742-1e563e99-e720-4689-8cca-fe19d4b8f33c.jpg)
![a3](https://user-images.githubusercontent.com/1125748/127738744-603a888a-5c43-4cda-942c-e29a2a066afb.jpg)
![a4](https://user-images.githubusercontent.com/1125748/127738745-4606272e-a5ee-4023-af99-f99500fea2c3.jpg)
![a5](https://user-images.githubusercontent.com/1125748/127738747-d12b5135-dd09-4f0c-a11f-7482e66e0b36.jpg)

**Comment by HadesArchitect** [comment]
Hey **Julian Nadarzy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZmHk3fC7Siu9yDrq1tksNQ
