### ISSUE TITLE
[HW] <Goh Kim Seng>

### ISSUE THREAD

**Issue by Kim-Seng** [datastaxdevs/workshop-intro-to-cassandra#257]
**Name:** Goh Kim Seng
**Email:** kimseng.goh@gmail.com
**Linkedin Profile:** www.linkedin.com/in/kim-seng

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

<SCREENSHOT>
![image](https://user-images.githubusercontent.com/87450520/128174746-a857a832-74d2-4356-adb9-02ac733bb14e.png)
![image](https://user-images.githubusercontent.com/87450520/128174887-934d04b6-4b33-4727-aabb-edea716183a1.png)
![image](https://user-images.githubusercontent.com/87450520/128174924-2e55a1f0-d6f6-4f21-b943-cef4677b765b.png)

**Comment by hemidactylus** [comment]
Hello there,
great job! It seems that you uploaded the final screen of the same scenario twice. Please add a screenshot of the completed "data model" scenario, https://www.datastax.com/node/3272 , to finish the homework.
See you soon and keep up the good work!

**Comment by Kim-Seng** [comment]
Name: Goh Kim Seng
Email: kimseng.goh@gmail.com
Linkedin Profile: www.linkedin.com/in/kim-seng

[Screenshots from Intro to Cassandra.docx](https://github.com/datastaxdevs/workshop-intro-to-cassandra/files/6973349/Screenshots.from.Intro.to.Cassandra.docx)
