### ISSUE TITLE
[HW] Aruna Koduvatte

### ISSUE THREAD

**Issue by aruna-valsan** [datastaxdevs/workshop-intro-to-cassandra#285]
**Name:** Aruna Koduvatte 
**Email:** arunavalsan1995@gmail.com 
**Linkedin Profile:** https://www.linkedin.com/in/aruna-k-197598171

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

![Screenshot_20210811-212250_Chrome](https://user-images.githubusercontent.com/88794469/129075426-60f275b5-577a-40d2-b64a-18ed016a184d.jpg)

**Comment by 000** [comment]
You may need to attach "Congratulations!" screenshots from https://www.datastax.com/node/3272 and https://www.datastax.com/dev/scenario/try-it-out-cassandra-query-language-cql as well, @aruna-valsan .

**Comment by aruna-valsan** [comment]
![Screenshot_20210812-173625_Chrome](https://user-images.githubusercontent.com/88794469/129206553-f8b0a167-df77-49fa-8219-22a468ff2ef7.jpg)
![Screenshot_20210812-173232_Chrome](https://user-images.githubusercontent.com/88794469/129206586-2a04f31d-b91c-40fd-bb99-390ab2982a5a.jpg)

**Comment by aruna-valsan** [comment]
I have attached both screen shots

**Comment by 000** [comment]
> I have attached both screen shots

Since you haven't received the badge yet, you may want to reopen your issue and wait to the DataStax team to check your screenshots first, @aruna-valsan .

**Comment by HadesArchitect** [comment]
Hey **Aruna Koduvatte**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/f9j43cqVRf2yZUYEvaHU-A
