### ISSUE TITLE
[HW] <PraveenSahu>

### ISSUE THREAD

**Issue by praveenitb** [datastaxdevs/workshop-intro-to-cassandra#345]
**Name:** PraveenSahu
**Email:** praveenitb@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/praveen-sahu-14816320/
![CassandaraBasicCapture](https://user-images.githubusercontent.com/47267072/129341356-d920b6e5-3e78-413d-b582-d6b85d4cfd43.JPG)
>

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

<SCREENSHOT>

**Comment by hemidactylus** [comment]
Hello there! Great job so far!
You should also finish the two "short courses" as described in https://github.com/datastaxdevs/workshop-intro-to-cassandra#homework and add the screenshots of their "Congratulations" screen, so we can grade the homework as done and award you the badge!
Thank you and see you soon!

**Comment by praveenitb** [comment]
![Cassandra Data Modeling](https://user-images.githubusercontent.com/47267072/129383052-7d4e88c6-988e-401a-ab00-6216e3ef2008.JPG)
![Cassandra_CQL](https://user-images.githubusercontent.com/47267072/129383065-2029620a-a46e-4566-afd3-a6b25c79bf74.JPG)

**Comment by praveenitb** [comment]
Please review. Now completed both the modules . PFA the screenshot.

**Comment by HadesArchitect** [comment]
Hey **PraveenSahu**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/dp6h5Z2SR6KKUlo9PEt5Ew
