### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by JesseObed-jesse** [datastaxdevs/workshop-intro-to-cassandra#372]
**Name:** <Jesse Obed>
**Email:** <jesseobed0910@gmail.com>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

<![image](https://user-images.githubusercontent.com/77734325/133437429-a100ff2a-75ac-4e89-9b47-e937f2279a2b.png)>

**Comment by SonicDMG** [comment]
Closed as duplicate
