### ISSUE TITLE
[HW] <IBNU HAIDAR>

### ISSUE THREAD

**Issue by IbnuHaidar** [datastaxdevs/workshop-intro-to-cassandra#384]
**Name:** Ibnu Haidar
**Email:** alhaidar.ibnu@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ibnuhaidar/

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

![after delete](https://user-images.githubusercontent.com/91370117/134766934-b1156f7c-64fb-4380-a9e1-e154907c57b4.jpg)
![before delete](https://user-images.githubusercontent.com/91370117/134766945-f1573a97-1c73-400b-9c06-bd4768f13b46.jpg)

**Comment by IbnuHaidar** [comment]
Thank all instructors

**Comment by SonicDMG** [comment]
Hey there Ibnu, thank you for your submission. Nice job getting Through the workshop materials. The only thing we are missing is step 3 of the homework.
3. Complete the following short courses: [Cassandra Data Modeling](https://www.datastax.com/node/3272) and [Cassandra Query Language](https://www.datastax.com/dev/scenario/try-it-out-cassandra-query-language-cql). Take screenshots of the "Congratulations" page from each course.

Please post an image of the "completed" screen once finished.
