### ISSUE TITLE
[HW] Pavan Kumar Dittakavi

### ISSUE THREAD

**Issue by pawanit17** [datastaxdevs/workshop-intro-to-cassandra#385]
**Name:** Pavan Kumar Dittakavi
**Email:** pawan.it17@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/dittakavipavankumar/

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

![image](https://user-images.githubusercontent.com/42272776/134807035-862b6e5d-9288-46c1-bddb-bfd8e913542a.png)
I completed the course, please let me know if anything else is to be done from my end. Thanks for the great course!.

**Comment by SonicDMG** [comment]
Hey there Pavan, thank you for your submission. Nice job getting Through the workshop materials. The only thing we are missing is step 3 of the homework.
3. Complete the following short courses: [Cassandra Data Modeling](https://www.datastax.com/node/3272) and [Cassandra Query Language](https://www.datastax.com/dev/scenario/try-it-out-cassandra-query-language-cql). Take screenshots of the "Congratulations" page from each course.

Please post an image of the "completed" screen once finished.

**Comment by pawanit17** [comment]
I see that the issue got closed. I am not sure if this is intended. Please let me know.

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Pavan Kumar Dittakavi

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/cHrjhbjIR0WijlVeMxraLA

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>
