### ISSUE TITLE
[HW] Ivan Gninenko

### ISSUE THREAD

**Issue by ivanmclennon** [datastaxdevs/workshop-intro-to-cassandra#75]
**Name:** Ivan Gninenko
**Email:** iagninenko@edu.hse.ru
**Linkedin Profile:** 

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

![image](https://user-images.githubusercontent.com/16653259/117159884-5457bd00-adc9-11eb-9082-c1dda3989c83.png)
![image](https://user-images.githubusercontent.com/16653259/117159908-59b50780-adc9-11eb-9aba-65249053027c.png)
![image](https://user-images.githubusercontent.com/16653259/117159924-5de12500-adc9-11eb-88e3-50f90e4e5b43.png)

**Comment by SonicDMG** [comment]
Looks good Ivan, thank you.

**Comment by HadesArchitect** [comment]
Great job! https://api.badgr.io/public/assertions/6_n25oAqRQKFhgw8kabbSw?identity__email=iagninenko%40edu.hse.ru

**Comment by ivanmclennon** [comment]
Thanks guys
